import { ToolDefinition } from '../types';

export const ROADMAP_TOOLS: ToolDefinition[] = [
  {
    id: 'tool-percentage-calc',
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'Calculate percentage increase, decrease, fraction percentages, and common discount rates.',
    description: 'Comprehensive percentage calculator for everyday math, finance, and shopping calculations.',
    category: 'math-calculators',
    icon: 'Percent',
    keywords: ['percentage', 'calculator', 'discount', 'percent increase', 'math'],
    executionMode: 'client',
    status: 'coming_soon',
    seo: {
      title: 'Free Online Percentage Calculator',
      description: 'Quick percentage calculations for increases, decreases, and fractions.',
      keywords: ['percentage calculator', 'calculate percent'],
    },
  },
  {
    id: 'tool-emi-calc',
    slug: 'emi-calculator',
    name: 'EMI & Loan Calculator',
    shortDescription: 'Calculate monthly installment payments, interest breakdown, and amortization schedule.',
    description: 'Accurate loan EMI calculator with monthly breakdown and total interest calculations.',
    category: 'finance',
    icon: 'PiggyBank',
    keywords: ['emi', 'loan', 'calculator', 'mortgage', 'interest rate'],
    executionMode: 'client',
    status: 'coming_soon',
    seo: {
      title: 'Free Loan & EMI Calculator',
      description: 'Calculate loan EMI and monthly interest schedules.',
      keywords: ['emi calculator', 'loan calculator'],
    },
  },
  {
    id: 'tool-url-encoder',
    slug: 'url-encoder-decoder',
    name: 'URL Encoder & Decoder',
    shortDescription: 'Encode and decode URI components and query strings compliant with RFC 3986.',
    description: 'Convert characters to percent-encoded equivalents or decode query parameters.',
    category: 'web-seo',
    icon: 'Link',
    keywords: ['url encode', 'url decode', 'uri component', 'percent encoding'],
    executionMode: 'client',
    status: 'coming_soon',
    seo: {
      title: 'Free Online URL Encoder / Decoder',
      description: 'Encode and decode URLs with full RFC 3986 compliance.',
      keywords: ['url encoder', 'url decoder'],
    },
  },
  {
    id: 'tool-uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    shortDescription: 'Generate cryptographically secure v4 UUIDs individually or in bulk.',
    description: 'Generate standard RFC 4122 Version 4 UUIDs using window.crypto API.',
    category: 'everyday-utilities',
    icon: 'KeyRound',
    keywords: ['uuid', 'guid', 'v4 uuid', 'random generator'],
    executionMode: 'client',
    status: 'coming_soon',
    seo: {
      title: 'Free Cryptographic UUID Generator',
      description: 'Generate RFC 4122 v4 UUIDs directly in your browser.',
      keywords: ['uuid generator', 'guid generator'],
    },
  },
  {
    id: 'tool-image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress PNG, JPEG, and WebP images client-side using browser canvas.',
    description: 'Reduce image file sizes directly in browser memory without sending files to any server.',
    category: 'image-graphics',
    icon: 'FileImage',
    keywords: ['image compressor', 'compress png', 'compress jpeg', 'webp'],
    executionMode: 'client',
    status: 'coming_soon',
    seo: {
      title: 'Private In-Browser Image Compressor',
      description: 'Compress images client-side without uploading files to a server.',
      keywords: ['image compressor', 'client side image compression'],
    },
  },
  {
    id: 'tool-pdf-merge',
    slug: 'pdf-merger',
    name: 'PDF Merger',
    shortDescription: 'Combine multiple PDF documents into a single ordered file.',
    description: 'Fast, secure PDF merging utility.',
    category: 'pdf-files',
    icon: 'Files',
    keywords: ['pdf merge', 'combine pdf', 'join pdf'],
    executionMode: 'hybrid',
    status: 'coming_soon',
    seo: {
      title: 'Free PDF Merger Tool',
      description: 'Merge and combine PDF documents with zero data retention.',
      keywords: ['pdf merger', 'combine pdfs online'],
    },
  },
];
