import { ToolMetadata } from './types';

export const textToolsRegistry: ToolMetadata[] = [
  {
    id: 'tool-word-counter',
    slug: 'word-counter',
    name: 'Word & Text Counter',
    category: 'text',
    description: 'Detailed real-time text analysis. Count words, characters, sentences, paragraphs, and estimate reading time.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-case-converter',
    slug: 'case-converter',
    name: 'Text Case Converter',
    category: 'text',
    description: 'Transform text into 9 standard capitalization formats: UPPERCASE, lowercase, Title Case, camelCase, snake_case, and more.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-duplicate-line-remover',
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    category: 'text',
    description: 'Clean text lists and data files by eliminating duplicate lines with case-sensitivity and whitespace options.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-text-diff',
    slug: 'text-diff',
    name: 'Text Diff & Comparison Tool',
    category: 'text',
    description: 'Compare two text documents or code snippets side-by-side with color-coded additions, deletions, and line numbers.',
    status: 'active',
    workspaceType: 'TextDiffWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-sort-lines',
    slug: 'sort-lines',
    name: 'Sort Lines',
    category: 'text',
    description: 'Sort lines alphabetically (A-Z, Z-A), numerically, or by line length with case-sensitivity options.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-reverse-text',
    slug: 'reverse-text',
    name: 'Reverse Text & Lines',
    category: 'text',
    description: 'Reverse text characters or flip line ordering from bottom to top with one click.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-whitespace-cleaner',
    slug: 'whitespace-cleaner',
    name: 'Whitespace Cleaner & Trimmer',
    category: 'text',
    description: 'Clean up formatted text by stripping redundant whitespace, collapsing multiple spaces, and removing empty lines.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-line-numbers',
    slug: 'line-numbers',
    name: 'Add / Remove Line Numbers',
    category: 'text',
    description: 'Add sequential line numbering with custom separators or strip existing line numbers from text snippets.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-text-extractor',
    slug: 'text-extractor',
    name: 'Extract Emails, URLs & Numbers',
    category: 'text',
    description: 'Extract email addresses, web links, numbers, hashtags, and @mentions from unformatted text documents.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-slug-generator',
    slug: 'slug-generator',
    name: 'URL Slug Generator',
    category: 'text',
    description: 'Convert headlines and titles into clean, web-safe, SEO-friendly URL slugs with custom separators.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
  {
    id: 'tool-lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    category: 'text',
    description: 'Generate customizable placeholder dummy text in paragraphs, sentences, words, or HTML lists.',
    status: 'active',
    workspaceType: 'TextWorkspace',
    supportedFormats: ['.txt'],
  },
];
