import { PublicWorkspace } from './workspace-types';

export const imageWorkspaces: PublicWorkspace[] = [
  {
    id: 'ws-image-editor',
    slug: 'image-editor',
    name: 'Image Editor',
    category: 'image',
    description: 'All-in-one visual editor: crop, resize, rotate, flip, draw, add text, apply filters, and adjust colors.',
    icon: 'SlidersHorizontal',
    defaultModeId: 'edit',
    badge: 'Popular',
    searchableAliases: ['edit image', 'crop image', 'resize image', 'photo editor', 'image filters'],
    capabilitySlugs: [
      'image-editor', 'crop-image', 'resize-image', 'rotate-image', 'flip-image',
      'image-watermark', 'add-text-to-image', 'draw-on-image', 'image-filters',
      'image-adjustments', 'brightness-contrast', 'image-color-adjustments',
      'grayscale-image', 'blur-image', 'sharpen-image'
    ],
    modes: [
      {
        id: 'edit',
        label: 'Image Editor',
        description: 'Comprehensive canvas to retouch, annotate, and transform graphics.',
        capabilitySlug: 'image-editor',
        aliases: ['edit photo', 'photo retouch'],
      },
      {
        id: 'crop',
        label: 'Crop Image',
        description: 'Trim borders with preset aspect ratios (1:1, 16:9, 4:3) or freehand selection.',
        capabilitySlug: 'crop-image',
        aliases: ['cut image', 'crop picture'],
      },
      {
        id: 'resize',
        label: 'Resize Image',
        description: 'Scale pixel dimensions or percentage while maintaining aspect ratios.',
        capabilitySlug: 'resize-image',
        aliases: ['scale image', 'change dimensions'],
      },
      {
        id: 'rotate',
        label: 'Rotate Image',
        description: 'Rotate 90, 180, or 270 degrees or straighten tilted photos.',
        capabilitySlug: 'rotate-image',
        aliases: ['turn image', 'rotate picture'],
      },
      {
        id: 'flip',
        label: 'Flip Image',
        description: 'Mirror photos horizontally or vertically with one click.',
        capabilitySlug: 'flip-image',
        aliases: ['mirror image', 'horizontal flip'],
      },
      {
        id: 'watermark',
        label: 'Image Watermark',
        description: 'Overlay custom text copyright marks or translucent PNG logo stamps.',
        capabilitySlug: 'image-watermark',
        aliases: ['watermark photo', 'brand image'],
      },
      {
        id: 'add-text',
        label: 'Add Text',
        description: 'Type captions, headlines, and callouts with custom typography.',
        capabilitySlug: 'add-text-to-image',
        aliases: ['write on image', 'caption photo'],
      },
      {
        id: 'draw',
        label: 'Draw',
        description: 'Freehand markup brush for sketching arrows, notes, and highlights.',
        capabilitySlug: 'draw-on-image',
        aliases: ['pen tool', 'sketch on photo'],
      },
      {
        id: 'filters',
        label: 'Image Filters',
        description: 'Apply artistic filters: sepia, vintage, dramatic, warm, and cool tone presets.',
        capabilitySlug: 'image-filters',
        aliases: ['photo filters', 'color effects'],
      },
      {
        id: 'adjustments',
        label: 'Image Adjustments',
        description: 'Fine-tune exposure, saturation, vibrance, warmth, and tint.',
        capabilitySlug: 'image-adjustments',
        aliases: ['color grade', 'photo tweaks'],
      },
      {
        id: 'brightness-contrast',
        label: 'Brightness & Contrast',
        description: 'Boost lighting in dark photos and balance tonal contrast curves.',
        capabilitySlug: 'brightness-contrast',
        aliases: ['exposure tool', 'lighten image'],
      },
      {
        id: 'color-adjustments',
        label: 'Color Adjustments',
        description: 'Adjust hue rotation, color balance, and chromatic channels.',
        capabilitySlug: 'image-color-adjustments',
        aliases: ['hue adjust', 'tint photo'],
      },
      {
        id: 'grayscale',
        label: 'Grayscale Image',
        description: 'Convert colored pictures into expressive black & white portraits.',
        capabilitySlug: 'grayscale-image',
        aliases: ['b&w photo', 'monochrome image'],
      },
      {
        id: 'blur',
        label: 'Blur Image',
        description: 'Apply Gaussian blur to soften backgrounds or obscure sensitive details.',
        capabilitySlug: 'blur-image',
        aliases: ['gaussian blur', 'soften photo'],
      },
      {
        id: 'sharpen',
        label: 'Sharpen Image',
        description: 'Enhance edge contrast and clarity in slightly fuzzy captures.',
        capabilitySlug: 'sharpen-image',
        aliases: ['unsharp mask', 'crisp image'],
      },
    ],
  },
  {
    id: 'ws-image-compressor-optimizer',
    slug: 'image-compressor-optimizer',
    name: 'Image Compressor & Optimizer',
    category: 'image',
    description: 'Lossless and lossy compression engine for JPG, PNG, and WebP assets to maximize web performance.',
    icon: 'FileArchive',
    defaultModeId: 'compressor',
    badge: 'Popular',
    searchableAliases: ['compress image', 'optimize jpg', 'reduce image size', 'compress png', 'webp compressor'],
    capabilitySlugs: [
      'image-compressor', 'jpg-compressor', 'png-compressor', 'webp-compressor',
      'image-optimizer', 'reduce-image-size', 'optimize-jpg', 'optimize-png'
    ],
    modes: [
      {
        id: 'compressor',
        label: 'Image Compressor',
        description: 'Smart auto-compression balancing high fidelity and tiny file sizes.',
        capabilitySlug: 'image-compressor',
        aliases: ['compress picture', 'shrink image'],
      },
      {
        id: 'jpg-compressor',
        label: 'JPG Compressor',
        description: 'Dedicated DCT quantization compression optimized for JPEG photos.',
        capabilitySlug: 'jpg-compressor',
        aliases: ['compress jpeg', 'reduce jpg size'],
      },
      {
        id: 'png-compressor',
        label: 'PNG Compressor',
        description: 'Lossless DEFLATE and color-palette reduction for transparent PNGs.',
        capabilitySlug: 'png-compressor',
        aliases: ['compress png file', 'tiny png'],
      },
      {
        id: 'webp-compressor',
        label: 'WebP Compressor',
        description: 'Next-gen Google WebP compression yielding up to 80% bandwidth savings.',
        capabilitySlug: 'webp-compressor',
        aliases: ['compress webp', 'shrink webp'],
      },
      {
        id: 'optimizer',
        label: 'Image Optimizer',
        description: 'Bulk web asset optimizer stripping redundant headers and color chunks.',
        capabilitySlug: 'image-optimizer',
        aliases: ['web image optimizer', 'speed up images'],
      },
      {
        id: 'reduce-size',
        label: 'Reduce Image Size',
        description: 'Target exact file sizes in KB or MB for email attachments and portal uploads.',
        capabilitySlug: 'reduce-image-size',
        aliases: ['shrink kb', 'target file size'],
      },
      {
        id: 'optimize-jpg',
        label: 'Optimize JPG',
        description: 'Progressive JPEG encoding for faster perception over mobile networks.',
        capabilitySlug: 'optimize-jpg',
        aliases: ['progressive jpeg', 'jpeg optimization'],
      },
      {
        id: 'optimize-png',
        label: 'Optimize PNG',
        description: 'Quantize 24-bit PNG assets into lightweight 8-bit index PNG palettes.',
        capabilitySlug: 'optimize-png',
        aliases: ['pngquant', 'png palette optimizer'],
      },
    ],
  },
  {
    id: 'ws-image-converter',
    slug: 'image-converter',
    name: 'Image Converter',
    category: 'image',
    description: 'Universal image format conversion between JPG, PNG, WebP, GIF, BMP, and TIFF.',
    icon: 'RefreshCw',
    defaultModeId: 'jpg-to-png',
    badge: 'Popular',
    searchableAliases: ['jpg to png', 'png to jpg', 'jpg to webp', 'png to webp', 'webp to jpg', 'convert images'],
    capabilitySlugs: [
      'jpg-to-png', 'png-to-jpg', 'jpg-to-webp', 'png-to-webp', 'webp-to-jpg',
      'webp-to-png', 'jpg-to-gif', 'png-to-gif', 'gif-to-jpg', 'gif-to-png',
      'gif-to-webp', 'bmp-to-jpg', 'bmp-to-png', 'tiff-to-jpg', 'images-to-jpg',
      'images-to-png', 'images-to-webp'
    ],
    modes: [
      {
        id: 'jpg-to-png',
        label: 'JPG → PNG',
        description: 'Convert JPEG images to lossless PNG format with clean edges.',
        capabilitySlug: 'jpg-to-png',
        aliases: ['jpeg to png'],
        outputFormats: ['.png'],
      },
      {
        id: 'png-to-jpg',
        label: 'PNG → JPG',
        description: 'Convert transparent or heavy PNG illustrations to compact JPEG photos.',
        capabilitySlug: 'png-to-jpg',
        aliases: ['png to jpeg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'jpg-to-webp',
        label: 'JPG → WebP',
        description: 'Transform JPG photos into modern, lightning-fast WebP web assets.',
        capabilitySlug: 'jpg-to-webp',
        aliases: ['jpeg to webp'],
        outputFormats: ['.webp'],
      },
      {
        id: 'png-to-webp',
        label: 'PNG → WebP',
        description: 'Convert PNG graphics to WebP preserving full alpha transparency.',
        capabilitySlug: 'png-to-webp',
        aliases: ['transparent webp converter'],
        outputFormats: ['.webp'],
      },
      {
        id: 'webp-to-jpg',
        label: 'WebP → JPG',
        description: 'Convert downloaded WebP web graphics back into universal JPEG files.',
        capabilitySlug: 'webp-to-jpg',
        aliases: ['webp to jpeg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'webp-to-png',
        label: 'WebP → PNG',
        description: 'Convert modern WebP graphics to widely compatible PNG documents.',
        capabilitySlug: 'webp-to-png',
        aliases: ['webp to png converter'],
        outputFormats: ['.png'],
      },
      {
        id: 'jpg-to-gif',
        label: 'JPG → GIF',
        description: 'Transform still JPG pictures into web-compatible GIF graphics.',
        capabilitySlug: 'jpg-to-gif',
        aliases: ['convert jpg to gif'],
        outputFormats: ['.gif'],
      },
      {
        id: 'png-to-gif',
        label: 'PNG → GIF',
        description: 'Convert PNG banners and logos to compact 256-color GIF format.',
        capabilitySlug: 'png-to-gif',
        aliases: ['png to gif banner'],
        outputFormats: ['.gif'],
      },
      {
        id: 'gif-to-jpg',
        label: 'GIF → JPG',
        description: 'Extract still frames or convert GIF graphics into standard JPEGs.',
        capabilitySlug: 'gif-to-jpg',
        aliases: ['gif to jpeg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'gif-to-png',
        label: 'GIF → PNG',
        description: 'Turn GIF art into high-resolution PNGs with transparent backgrounds.',
        capabilitySlug: 'gif-to-png',
        aliases: ['gif to transparent png'],
        outputFormats: ['.png'],
      },
      {
        id: 'gif-to-webp',
        label: 'GIF → WebP',
        description: 'Convert bulky animated or still GIFs to lightweight WebP files.',
        capabilitySlug: 'gif-to-webp',
        aliases: ['animated webp converter'],
        outputFormats: ['.webp'],
      },
      {
        id: 'bmp-to-jpg',
        label: 'BMP → JPG',
        description: 'Compress uncompressed Windows bitmap files into modern JPEGs.',
        capabilitySlug: 'bmp-to-jpg',
        aliases: ['bitmap to jpeg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'bmp-to-png',
        label: 'BMP → PNG',
        description: 'Convert legacy BMP bitmaps to clean lossless PNG format.',
        capabilitySlug: 'bmp-to-png',
        aliases: ['bitmap to png'],
        outputFormats: ['.png'],
      },
      {
        id: 'tiff-to-jpg',
        label: 'TIFF → JPG',
        description: 'Convert raw scanner TIFF images into shareable JPEG photos.',
        capabilitySlug: 'tiff-to-jpg',
        aliases: ['tif to jpeg', 'scanner to jpg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'images-to-jpg',
        label: 'Images → JPG',
        description: 'Batch convert mixed image formats simultaneously into standard JPGs.',
        capabilitySlug: 'images-to-jpg',
        aliases: ['batch jpg converter', 'bulk convert to jpg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'images-to-png',
        label: 'Images → PNG',
        description: 'Batch convert mixed formats simultaneously into clean PNGs.',
        capabilitySlug: 'images-to-png',
        aliases: ['batch png converter', 'bulk convert to png'],
        outputFormats: ['.png'],
      },
      {
        id: 'images-to-webp',
        label: 'Images → WebP',
        description: 'Batch convert your photo library into next-gen WebP formats.',
        capabilitySlug: 'images-to-webp',
        aliases: ['batch webp converter', 'bulk webp'],
        outputFormats: ['.webp'],
      },
    ],
  },
  {
    id: 'ws-image-combiner-collage',
    slug: 'image-combiner-collage',
    name: 'Image Combiner & Collage',
    category: 'image',
    description: 'Merge multiple images side-by-side, build photo collages, split photos into grids, and add borders.',
    icon: 'Grid',
    defaultModeId: 'combine',
    searchableAliases: ['combine images', 'merge images', 'photo collage', 'image splitter', 'image frames'],
    capabilitySlugs: [
      'combine-images', 'merge-images', 'image-collage-maker', 'image-splitter', 'image-frame', 'rounded-image'
    ],
    modes: [
      {
        id: 'combine',
        label: 'Combine Images',
        description: 'Join photos horizontally or vertically into a seamless panoramic strip.',
        capabilitySlug: 'combine-images',
        aliases: ['stitch photos', 'horizontal photo merge'],
      },
      {
        id: 'merge',
        label: 'Merge Images',
        description: 'Stack multiple layers with customizable blending modes and opacity.',
        capabilitySlug: 'merge-images',
        aliases: ['blend images', 'layer photos'],
      },
      {
        id: 'collage',
        label: 'Image Collage',
        description: 'Arrange multiple snapshots into creative masonry and grid layouts.',
        capabilitySlug: 'image-collage-maker',
        aliases: ['photo collage maker', 'grid collage'],
      },
      {
        id: 'splitter',
        label: 'Image Splitter',
        description: 'Divide high-res pictures into 2x2, 3x3, or custom tiles for social grids.',
        capabilitySlug: 'image-splitter',
        aliases: ['slice image', 'grid cutter'],
      },
      {
        id: 'frame',
        label: 'Image Frame',
        description: 'Surround your pictures with decorative borders, shadows, and paddings.',
        capabilitySlug: 'image-frame',
        aliases: ['photo border', 'add picture frame'],
      },
      {
        id: 'rounded',
        label: 'Rounded Image',
        description: 'Smooth photo corners with customizable radius or circular avatar masks.',
        capabilitySlug: 'rounded-image',
        aliases: ['round corners', 'circle avatar crop'],
      },
    ],
  },
  {
    id: 'ws-image-background-editor',
    slug: 'image-background-editor',
    name: 'Background Editor',
    category: 'image',
    description: 'Remove backgrounds, isolate subjects, make transparent PNGs, and replace backdrop colors.',
    icon: 'Image',
    defaultModeId: 'remove-background',
    badge: 'Popular',
    searchableAliases: ['remove background', 'transparent background', 'transparent png', 'replace background'],
    capabilitySlugs: [
      'image-background-color', 'remove-image-background', 'make-image-background-transparent',
      'add-background-to-image', 'replace-image-background', 'remove-white-background',
      'transparent-png-maker'
    ],
    modes: [
      {
        id: 'background-color',
        label: 'Background Color',
        description: 'Fill transparent backdrop areas with custom solid or gradient colors.',
        capabilitySlug: 'image-background-color',
        aliases: ['fill backdrop', 'change bg color'],
      },
      {
        id: 'remove-background',
        label: 'Remove Background',
        description: 'Isolate main subjects and remove surrounding backgrounds automatically.',
        capabilitySlug: 'remove-image-background',
        aliases: ['cut out subject', 'bg remover'],
      },
      {
        id: 'transparent-background',
        label: 'Transparent Background',
        description: 'Convert solid backgrounds into clear, transparent alpha channels.',
        capabilitySlug: 'make-image-background-transparent',
        aliases: ['clear background', 'alpha cutout'],
      },
      {
        id: 'add-background',
        label: 'Add Background',
        description: 'Insert scenic backdrop wallpapers or textures behind isolated objects.',
        capabilitySlug: 'add-background-to-image',
        aliases: ['insert background', 'composite backdrop'],
      },
      {
        id: 'replace-background',
        label: 'Replace Background',
        description: 'Swap existing environments with new studio, office, or scenic scenes.',
        capabilitySlug: 'replace-image-background',
        aliases: ['swap backdrop', 'change background scene'],
      },
      {
        id: 'remove-white',
        label: 'Remove White Background',
        description: 'Instantly key out pure white backdrop pixels from e-commerce product photos.',
        capabilitySlug: 'remove-white-background',
        aliases: ['strip white bg', 'product photo cutout'],
      },
      {
        id: 'transparent-png',
        label: 'Transparent PNG',
        description: 'Export clean transparent PNG graphics ready for website placement.',
        capabilitySlug: 'transparent-png-maker',
        aliases: ['make transparent png', 'export transparent cutout'],
      },
    ],
  },
  {
    id: 'ws-image-info-metadata',
    slug: 'image-info-metadata',
    name: 'Image Info & Metadata',
    category: 'image',
    description: 'Inspect camera EXIF data, GPS location coordinates, color profiles, and strip tracking metadata.',
    icon: 'Info',
    defaultModeId: 'metadata-viewer',
    searchableAliases: ['exif viewer', 'remove metadata', 'image info', 'dimensions checker'],
    capabilitySlugs: [
      'image-metadata-viewer', 'remove-image-metadata', 'exif-viewer', 'image-information', 'image-dimensions-checker'
    ],
    modes: [
      {
        id: 'metadata-viewer',
        label: 'Metadata Viewer',
        description: 'Inspect comprehensive EXIF, IPTC, and XMP photographic properties.',
        capabilitySlug: 'image-metadata-viewer',
        aliases: ['view photo tags', 'image properties'],
      },
      {
        id: 'remove-metadata',
        label: 'Remove Metadata',
        description: 'Protect privacy by scrubbing GPS coordinates, camera serials, and timestamps.',
        capabilitySlug: 'remove-image-metadata',
        aliases: ['sanitize photo', 'strip exif'],
      },
      {
        id: 'exif-viewer',
        label: 'EXIF Viewer',
        description: 'Check shutter speed, aperture, ISO, focal length, and camera lens specs.',
        capabilitySlug: 'exif-viewer',
        aliases: ['camera settings viewer', 'iso viewer'],
      },
      {
        id: 'information',
        label: 'Image Information',
        description: 'Summary of file format, bit depth, compression type, and estimated DPI.',
        capabilitySlug: 'image-information',
        aliases: ['image specs', 'photo details'],
      },
      {
        id: 'dimensions-checker',
        label: 'Dimensions Checker',
        description: 'Instantly view exact pixel width, height, aspect ratio, and megapixel count.',
        capabilitySlug: 'image-dimensions-checker',
        aliases: ['check image resolution', 'aspect ratio check'],
      },
    ],
  },
  {
    id: 'ws-image-utilities',
    slug: 'image-utilities',
    name: 'Image Utilities',
    category: 'image',
    description: 'Helpful developer & designer utilities: eyedropper color picker and Base64 data URI encoder/decoder.',
    icon: 'Pipette',
    defaultModeId: 'color-picker',
    searchableAliases: ['color picker', 'image to base64', 'base64 to image', 'data uri converter'],
    capabilitySlugs: ['image-color-picker', 'image-to-base64', 'base64-to-image'],
    modes: [
      {
        id: 'color-picker',
        label: 'Image Color Picker',
        description: 'Inspect precise HEX, RGB, and HSL color values from any pixel in your photo.',
        capabilitySlug: 'image-color-picker',
        aliases: ['eyedropper', 'hex color sampler'],
      },
      {
        id: 'to-base64',
        label: 'Image → Base64',
        description: 'Encode binary images into embedded data:image Base64 strings for CSS/HTML.',
        capabilitySlug: 'image-to-base64',
        aliases: ['encode base64', 'image to data uri'],
      },
      {
        id: 'base64-to-image',
        label: 'Base64 → Image',
        description: 'Decode Base64 strings back into downloadable JPG or PNG files.',
        capabilitySlug: 'base64-to-image',
        aliases: ['decode base64', 'data uri to image'],
      },
    ],
  },
];
