import { PublicWorkspace } from './workspace-types';

export const pdfWorkspaces: PublicWorkspace[] = [
  {
    id: 'ws-pdf-organizer',
    slug: 'pdf-organizer',
    name: 'PDF Organizer',
    category: 'pdf',
    description: 'Comprehensive page-level organization, merging, splitting, reordering, and structural modifications.',
    icon: 'FolderTree',
    defaultModeId: 'merge',
    badge: 'Popular',
    searchableAliases: ['organize pdf', 'page manager', 'combine pdf', 'split pdf', 'rotate pages'],
    capabilitySlugs: [
      'merge-pdf', 'split-pdf', 'rotate-pdf', 'delete-pdf-pages', 'extract-pdf-pages',
      'rearrange-pdf-pages', 'crop-pdf', 'split-in-half', 'duplicate-pages', 'insert-pages',
      'replace-pages', 'organize-pdf', 'pdf-portfolio-operations', 'split-by-bookmark'
    ],
    modes: [
      {
        id: 'merge',
        label: 'Merge PDF',
        description: 'Combine multiple PDF documents into a single cohesive file.',
        capabilitySlug: 'merge-pdf',
        aliases: ['combine pdf', 'join pdf', 'concatenate pdf'],
      },
      {
        id: 'split',
        label: 'Split PDF',
        description: 'Separate one PDF into individual pages or custom page ranges.',
        capabilitySlug: 'split-pdf',
        aliases: ['separate pdf', 'cut pdf', 'divide pdf'],
      },
      {
        id: 'rotate',
        label: 'Rotate PDF',
        description: 'Rotate individual pages or entire documents 90, 180, or 270 degrees.',
        capabilitySlug: 'rotate-pdf',
        aliases: ['flip pdf pages', 'turn pdf'],
      },
      {
        id: 'delete-pages',
        label: 'Delete Pages',
        description: 'Remove unwanted pages permanently from your PDF file.',
        capabilitySlug: 'delete-pdf-pages',
        aliases: ['remove pdf pages', 'drop pages'],
      },
      {
        id: 'extract-pages',
        label: 'Extract Pages',
        description: 'Pull specific page ranges out into a new standalone PDF.',
        capabilitySlug: 'extract-pdf-pages',
        aliases: ['pull pages', 'export pages'],
      },
      {
        id: 'rearrange',
        label: 'Rearrange Pages',
        description: 'Visual drag-and-drop page reordering and sequence adjustments.',
        capabilitySlug: 'rearrange-pdf-pages',
        aliases: ['reorder pdf', 'sort pages'],
      },
      {
        id: 'crop',
        label: 'Crop PDF',
        description: 'Trim margins and adjust visual canvas boundaries for selected pages.',
        capabilitySlug: 'crop-pdf',
        aliases: ['trim pdf', 'cut borders'],
      },
      {
        id: 'split-half',
        label: 'Split in Half',
        description: 'Slice two-page booklet scans into individual single pages.',
        capabilitySlug: 'split-in-half',
        aliases: ['split booklet', 'cut page in two'],
      },
      {
        id: 'duplicate-pages',
        label: 'Duplicate Pages',
        description: 'Clone selected pages or forms inside your document.',
        capabilitySlug: 'duplicate-pages',
        aliases: ['clone pages', 'copy page'],
      },
      {
        id: 'insert-pages',
        label: 'Insert Pages',
        description: 'Add new blank pages or pages from another document.',
        capabilitySlug: 'insert-pages',
        aliases: ['add blank page', 'inject pages'],
      },
      {
        id: 'replace-pages',
        label: 'Replace Pages',
        description: 'Substitute outdated pages with updated sheets.',
        capabilitySlug: 'replace-pages',
        aliases: ['swap pages', 'update pages'],
      },
      {
        id: 'organize',
        label: 'Organize PDF',
        description: 'All-in-one visual grid manager to sort, rotate, and prune pages.',
        capabilitySlug: 'organize-pdf',
        aliases: ['pdf page manager', 'visual organizer'],
      },
      {
        id: 'portfolio',
        label: 'PDF Portfolio',
        description: 'Manage and inspect embedded document package portfolios.',
        capabilitySlug: 'pdf-portfolio-operations',
        aliases: ['portfolio manager', 'embedded documents'],
      },
      {
        id: 'split-by-bookmark',
        label: 'Split by Bookmark',
        description: 'Divide documents automatically at outline and chapter boundaries.',
        capabilitySlug: 'split-by-bookmark',
        aliases: ['split chapters', 'bookmark split'],
      },
    ],
  },
  {
    id: 'ws-pdf-editor',
    slug: 'pdf-editor',
    name: 'PDF Editor',
    category: 'pdf',
    description: 'Direct visual editing, text annotation, redacting, signing, watermarking, stamping, and markup.',
    icon: 'PenTool',
    defaultModeId: 'edit',
    badge: 'Popular',
    searchableAliases: ['edit pdf', 'annotate pdf', 'redact pdf', 'sign pdf', 'watermark pdf'],
    capabilitySlugs: [
      'pdf-editor', 'add-text', 'add-image', 'add-shapes', 'highlight-text',
      'redact-text', 'draw-on-pdf', 'whiteout-pdf', 'add-signature', 'add-stamp',
      'measure-pdf', 'add-watermark', 'remove-watermark', 'replace-text', 'edit-links',
      'sign-pdf'
    ],
    modes: [
      {
        id: 'edit',
        label: 'PDF Editor',
        description: 'Full-featured visual editor canvas for documents.',
        capabilitySlug: 'pdf-editor',
        aliases: ['edit document', 'modify pdf'],
      },
      {
        id: 'add-text',
        label: 'Add Text',
        description: 'Insert styled text labels, notes, and paragraphs anywhere.',
        capabilitySlug: 'add-text',
        aliases: ['type on pdf', 'write on pdf'],
      },
      {
        id: 'add-image',
        label: 'Add Image',
        description: 'Place logos, photos, and graphic assets onto PDF pages.',
        capabilitySlug: 'add-image',
        aliases: ['insert image', 'embed photo'],
      },
      {
        id: 'add-shapes',
        label: 'Add Shapes',
        description: 'Draw geometric rectangles, circles, arrows, and borders.',
        capabilitySlug: 'add-shapes',
        aliases: ['draw shapes', 'insert box'],
      },
      {
        id: 'highlight',
        label: 'Highlight',
        description: 'Emphasize important paragraphs with translucent markup colors.',
        capabilitySlug: 'highlight-text',
        aliases: ['highlight text', 'marker'],
      },
      {
        id: 'redact',
        label: 'Redact PDF',
        description: 'Irreversibly black out confidential text, numbers, and PII.',
        capabilitySlug: 'redact-text',
        aliases: ['blackout text', 'remove sensitive info', 'secure redact'],
      },
      {
        id: 'draw',
        label: 'Draw',
        description: 'Freehand pen tool for sketching, circling, and hand annotations.',
        capabilitySlug: 'draw-on-pdf',
        aliases: ['freehand draw', 'pen markup'],
      },
      {
        id: 'whiteout',
        label: 'Whiteout',
        description: 'Erase or mask unwanted visual elements with opaque blocks.',
        capabilitySlug: 'whiteout-pdf',
        aliases: ['erase pdf', 'mask elements'],
      },
      {
        id: 'signature',
        label: 'Add Signature',
        description: 'Draw, type, or upload your personalized legal signature.',
        capabilitySlug: 'add-signature',
        aliases: ['e-sign', 'sign document'],
      },
      {
        id: 'stamp',
        label: 'Add Stamp',
        description: 'Apply status stamps: APPROVED, CONFIDENTIAL, PAID, VOID.',
        capabilitySlug: 'add-stamp',
        aliases: ['rubber stamp', 'document badge'],
      },
      {
        id: 'measure',
        label: 'Measure PDF',
        description: 'Calibrate scale and measure physical distances in blueprints.',
        capabilitySlug: 'measure-pdf',
        aliases: ['dimension tool', 'ruler pdf'],
      },
      {
        id: 'watermark',
        label: 'Add Watermark',
        description: 'Imprint text or image copyright watermarks across all pages.',
        capabilitySlug: 'add-watermark',
        aliases: ['copyright stamp', 'overlay watermark'],
      },
      {
        id: 'remove-watermark',
        label: 'Remove Watermark',
        description: 'Detect and strip background watermarks and overlays.',
        capabilitySlug: 'remove-watermark',
        aliases: ['clear watermark', 'delete watermark'],
      },
      {
        id: 'replace-text',
        label: 'Replace Text',
        description: 'Search and substitute specific text phrases across documents.',
        capabilitySlug: 'replace-text',
        aliases: ['find and replace', 'change text'],
      },
      {
        id: 'edit-links',
        label: 'Edit Links',
        description: 'Inspect, insert, or repair clickable web URLs and cross-page links.',
        capabilitySlug: 'edit-links',
        aliases: ['add hyperlinks', 'url editor'],
      },
      {
        id: 'sign',
        label: 'Sign PDF',
        description: 'Formal digital signing flow with timestamp and signer certificates.',
        capabilitySlug: 'sign-pdf',
        aliases: ['digital signature', 'sign contract'],
      },
    ],
  },
  {
    id: 'ws-pdf-viewer-search',
    slug: 'pdf-viewer-search',
    name: 'PDF Viewer & Search',
    category: 'pdf',
    description: 'High-performance in-browser PDF reader with deep textual search and navigation.',
    icon: 'Search',
    defaultModeId: 'view',
    searchableAliases: ['read pdf', 'search text in pdf', 'pdf reader'],
    capabilitySlugs: ['pdf-viewer', 'search-pdf'],
    modes: [
      {
        id: 'view',
        label: 'View PDF',
        description: 'Smooth, responsive document viewing with thumbnail navigation.',
        capabilitySlug: 'pdf-viewer',
        aliases: ['open pdf', 'read pdf'],
      },
      {
        id: 'search',
        label: 'Search PDF',
        description: 'Find keyword occurrences with instant page highlights and jump navigation.',
        capabilitySlug: 'search-pdf',
        aliases: ['find in pdf', 'keyword search'],
      },
    ],
  },
  {
    id: 'ws-pdf-structure',
    slug: 'pdf-structure',
    name: 'PDF Structure',
    category: 'pdf',
    description: 'Manage document metadata, page numbering, Bates stamping, and navigational bookmarks.',
    icon: 'Layers',
    defaultModeId: 'page-numbers',
    searchableAliases: ['page numbers', 'bates numbering', 'bookmarks', 'metadata editor'],
    capabilitySlugs: [
      'add-page-numbers', 'add-bates-numbering', 'add-bookmarks', 'extract-bookmarks', 'edit-metadata'
    ],
    modes: [
      {
        id: 'page-numbers',
        label: 'Add Page Numbers',
        description: 'Insert header or footer page numbers with custom font and positioning.',
        capabilitySlug: 'add-page-numbers',
        aliases: ['number pages', 'page numbering'],
      },
      {
        id: 'bates-numbering',
        label: 'Bates Numbering',
        description: 'Apply legal identification numbering sequences across case files.',
        capabilitySlug: 'add-bates-numbering',
        aliases: ['legal numbering', 'bates stamp'],
      },
      {
        id: 'add-bookmarks',
        label: 'Add Bookmarks',
        description: 'Construct a clickable table of contents outline in the sidebar.',
        capabilitySlug: 'add-bookmarks',
        aliases: ['create bookmarks', 'document outline'],
      },
      {
        id: 'extract-bookmarks',
        label: 'Extract Bookmarks',
        description: 'Export document outlines and TOC structures as clean text.',
        capabilitySlug: 'extract-bookmarks',
        aliases: ['export outline', 'read bookmarks'],
      },
      {
        id: 'metadata',
        label: 'Edit Metadata',
        description: 'Update or sanitize title, author, subject, keywords, and creation dates.',
        capabilitySlug: 'edit-metadata',
        aliases: ['change author', 'pdf properties'],
      },
    ],
  },
  {
    id: 'ws-pdf-optimize',
    slug: 'pdf-optimize',
    name: 'PDF Optimize',
    category: 'pdf',
    description: 'Compress file sizes, repair broken structures, flatten interactive layers, and optimize for web streaming.',
    icon: 'Minimize2',
    defaultModeId: 'compress',
    badge: 'Essential',
    searchableAliases: ['compress pdf', 'reduce pdf size', 'repair pdf', 'flatten pdf', 'grayscale'],
    capabilitySlugs: [
      'compress-pdf', 'repair-pdf', 'flatten-pdf', 'grayscale-pdf', 'resize-pdf', 'fast-web-view'
    ],
    modes: [
      {
        id: 'compress',
        label: 'Compress PDF',
        description: 'Dramatically shrink document file size while preserving legibility.',
        capabilitySlug: 'compress-pdf',
        aliases: ['shrink pdf', 'reduce size', 'optimize pdf'],
      },
      {
        id: 'repair',
        label: 'Repair PDF',
        description: 'Rebuild corrupt headers, unreadable xref tables, and damaged trees.',
        capabilitySlug: 'repair-pdf',
        aliases: ['fix pdf', 'restore corrupted pdf'],
      },
      {
        id: 'flatten',
        label: 'Flatten PDF',
        description: 'Merge form fields, layers, and annotations into standard page content.',
        capabilitySlug: 'flatten-pdf',
        aliases: ['flatten layers', 'lock forms'],
      },
      {
        id: 'grayscale',
        label: 'Grayscale PDF',
        description: 'Convert colored pages and illustrations to monochrome black and white.',
        capabilitySlug: 'grayscale-pdf',
        aliases: ['black and white pdf', 'monochrome'],
      },
      {
        id: 'resize',
        label: 'Resize PDF',
        description: 'Change paper dimensions between Letter, A4, A3, Legal, and custom sizes.',
        capabilitySlug: 'resize-pdf',
        aliases: ['change page size', 'scale pdf'],
      },
      {
        id: 'fast-web-view',
        label: 'Fast Web View',
        description: 'Linearize PDF bytes for rapid page-by-page streaming over web connections.',
        capabilitySlug: 'fast-web-view',
        aliases: ['linearize pdf', 'web stream optimization'],
      },
    ],
  },
  {
    id: 'ws-pdf-forms',
    slug: 'pdf-forms',
    name: 'PDF Forms',
    category: 'pdf',
    description: 'Create interactive form templates, fill out digital forms, extract data fields, and clear inputs.',
    icon: 'ClipboardEdit',
    defaultModeId: 'fill-form',
    searchableAliases: ['fill form', 'create form', 'form fields', 'extract form data'],
    capabilitySlugs: [
      'create-form', 'fill-form', 'add-form-fields', 'extract-form-data', 'flatten-form', 'clear-form'
    ],
    modes: [
      {
        id: 'create-form',
        label: 'Create Form',
        description: 'Design fresh interactive forms with textboxes, checkboxes, and radio buttons.',
        capabilitySlug: 'create-form',
        aliases: ['build form', 'interactive form maker'],
      },
      {
        id: 'fill-form',
        label: 'Fill Form',
        description: 'Directly type into AcroForm and XFA fields and export completed records.',
        capabilitySlug: 'fill-form',
        aliases: ['complete form', 'fill pdf inputs'],
      },
      {
        id: 'add-fields',
        label: 'Add Form Fields',
        description: 'Place text boxes, drop-downs, and signatures into existing flat files.',
        capabilitySlug: 'add-form-fields',
        aliases: ['insert input', 'make fillable'],
      },
      {
        id: 'extract-data',
        label: 'Extract Form Data',
        description: 'Export all populated field keys and values into JSON or CSV summaries.',
        capabilitySlug: 'extract-form-data',
        aliases: ['export form fields', 'dump form data'],
      },
      {
        id: 'flatten-form',
        label: 'Flatten Form',
        description: 'Lock completed answers into the page to prevent further editing.',
        capabilitySlug: 'flatten-form',
        aliases: ['lock form', 'freeze inputs'],
      },
      {
        id: 'clear-form',
        label: 'Clear Form',
        description: 'Reset all form values and checkboxes back to empty blank states.',
        capabilitySlug: 'clear-form',
        aliases: ['reset form', 'wipe inputs'],
      },
    ],
  },
  {
    id: 'ws-pdf-security',
    slug: 'pdf-security',
    name: 'PDF Security',
    category: 'pdf',
    description: 'Industry-standard AES encryption, password removal, permissions management, and access controls.',
    icon: 'Lock',
    defaultModeId: 'protect',
    searchableAliases: ['password protect', 'unlock pdf', 'encrypt pdf', 'decrypt pdf', 'pdf permissions'],
    capabilitySlugs: [
      'protect-pdf', 'unlock-pdf', 'encrypt-pdf', 'decrypt-pdf', 'set-permissions', 'remove-password'
    ],
    modes: [
      {
        id: 'protect',
        label: 'Protect PDF',
        description: 'Secure your file with a strong user password before sharing.',
        capabilitySlug: 'protect-pdf',
        aliases: ['add password', 'lock pdf'],
      },
      {
        id: 'unlock',
        label: 'Unlock PDF',
        description: 'Remove security restrictions when you know the owner password.',
        capabilitySlug: 'unlock-pdf',
        aliases: ['unlock password', 'remove restriction'],
      },
      {
        id: 'encrypt',
        label: 'Encrypt PDF',
        description: 'Military-grade 128-bit and 256-bit AES cryptographic protection.',
        capabilitySlug: 'encrypt-pdf',
        aliases: ['aes encrypt', 'secure document'],
      },
      {
        id: 'decrypt',
        label: 'Decrypt PDF',
        description: 'Strip cryptographic wrapping from authorized files.',
        capabilitySlug: 'decrypt-pdf',
        aliases: ['aes decrypt', 'unencrypt pdf'],
      },
      {
        id: 'permissions',
        label: 'Set Permissions',
        description: 'Restrict or allow printing, copying text, modifying, or annotating.',
        capabilitySlug: 'set-permissions',
        aliases: ['allow printing', 'disable copy'],
      },
      {
        id: 'remove-password',
        label: 'Remove Password',
        description: 'Permanently remove open passwords from personal files.',
        capabilitySlug: 'remove-password',
        aliases: ['clear password', 'strip lock'],
      },
    ],
  },
  {
    id: 'ws-pdf-converter',
    slug: 'pdf-converter',
    name: 'PDF Converter',
    category: 'pdf',
    description: 'Export and convert PDF documents into Word, Excel, PowerPoint, images, web pages, and data formats.',
    icon: 'ArrowRightLeft',
    defaultModeId: 'to-word',
    badge: 'Popular',
    searchableAliases: ['pdf to word', 'pdf to excel', 'pdf to jpg', 'pdf to png', 'pdf to powerpoint'],
    capabilitySlugs: [
      'pdf-to-word', 'pdf-to-excel', 'pdf-to-powerpoint', 'pdf-to-jpg', 'pdf-to-png',
      'pdf-to-tiff', 'pdf-to-html', 'pdf-to-epub', 'pdf-to-rtf', 'pdf-to-text',
      'pdf-to-xml', 'pdf-to-json'
    ],
    modes: [
      {
        id: 'to-word',
        label: 'PDF → Word',
        description: 'Convert PDF files into fully editable Microsoft Word DOCX documents.',
        capabilitySlug: 'pdf-to-word',
        aliases: ['pdf to docx', 'pdf to word doc'],
        outputFormats: ['.docx'],
      },
      {
        id: 'to-excel',
        label: 'PDF → Excel',
        description: 'Extract tables and structured data rows into Microsoft Excel XLSX workbooks.',
        capabilitySlug: 'pdf-to-excel',
        aliases: ['pdf to xlsx', 'pdf table extraction'],
        outputFormats: ['.xlsx'],
      },
      {
        id: 'to-powerpoint',
        label: 'PDF → PowerPoint',
        description: 'Turn PDF slides into editable Microsoft PowerPoint PPTX decks.',
        capabilitySlug: 'pdf-to-powerpoint',
        aliases: ['pdf to pptx', 'pdf to slides'],
        outputFormats: ['.pptx'],
      },
      {
        id: 'to-jpg',
        label: 'PDF → JPG',
        description: 'Render document pages as sharp, high-resolution JPEG images.',
        capabilitySlug: 'pdf-to-jpg',
        aliases: ['export pdf as jpg', 'pdf to jpeg'],
        outputFormats: ['.jpg'],
      },
      {
        id: 'to-png',
        label: 'PDF → PNG',
        description: 'Convert PDF sheets into crisp lossless PNG images with transparency support.',
        capabilitySlug: 'pdf-to-png',
        aliases: ['export pdf as png', 'pdf to transparent png'],
        outputFormats: ['.png'],
      },
      {
        id: 'to-tiff',
        label: 'PDF → TIFF',
        description: 'Export multi-page high-fidelity TIFF graphics for archival printing.',
        capabilitySlug: 'pdf-to-tiff',
        aliases: ['pdf to tif', 'print tiff'],
        outputFormats: ['.tiff'],
      },
      {
        id: 'to-html',
        label: 'PDF → HTML',
        description: 'Translate PDF layout into responsive, web-ready HTML5 and CSS.',
        capabilitySlug: 'pdf-to-html',
        aliases: ['pdf to webpage', 'html export'],
        outputFormats: ['.html'],
      },
      {
        id: 'to-epub',
        label: 'PDF → EPUB',
        description: 'Format document text for e-readers, tablets, and digital book devices.',
        capabilitySlug: 'pdf-to-epub',
        aliases: ['make ebook', 'pdf to ereader'],
        outputFormats: ['.epub'],
      },
      {
        id: 'to-rtf',
        label: 'PDF → RTF',
        description: 'Extract formatted text into cross-platform Rich Text Format files.',
        capabilitySlug: 'pdf-to-rtf',
        aliases: ['rich text export'],
        outputFormats: ['.rtf'],
      },
      {
        id: 'to-text',
        label: 'PDF → Text',
        description: 'Extract clean plain text without formatting or styling baggage.',
        capabilitySlug: 'pdf-to-text',
        aliases: ['pdf to txt', 'dump text'],
        outputFormats: ['.txt'],
      },
      {
        id: 'to-xml',
        label: 'PDF → XML',
        description: 'Export document hierarchy and semantic structure into XML trees.',
        capabilitySlug: 'pdf-to-xml',
        aliases: ['pdf xml extraction'],
        outputFormats: ['.xml'],
      },
      {
        id: 'to-json',
        label: 'PDF → JSON',
        description: 'Parse pages, metadata, and extracted text blocks into clean JSON arrays.',
        capabilitySlug: 'pdf-to-json',
        aliases: ['pdf to json data'],
        outputFormats: ['.json'],
      },
    ],
  },
  {
    id: 'ws-convert-to-pdf',
    slug: 'convert-to-pdf',
    name: 'Convert to PDF',
    category: 'pdf',
    description: 'Transform Office files, images (JPG, PNG, WebP), web pages, and raw text into standard PDF documents.',
    icon: 'FileUp',
    defaultModeId: 'from-word',
    badge: 'Popular',
    searchableAliases: ['jpg to pdf', 'png to pdf', 'images to pdf', 'word to pdf', 'excel to pdf'],
    capabilitySlugs: [
      'word-to-pdf', 'excel-to-pdf', 'powerpoint-to-pdf', 'jpg-to-pdf', 'png-to-pdf',
      'images-to-pdf', 'html-to-pdf', 'document-to-pdf', 'rtf-to-pdf', 'text-to-pdf',
      'xml-to-pdf', 'json-to-pdf'
    ],
    modes: [
      {
        id: 'from-word',
        label: 'Word → PDF',
        description: 'Convert DOC and DOCX Word documents into universal PDF files.',
        capabilitySlug: 'word-to-pdf',
        aliases: ['docx to pdf', 'doc to pdf'],
        acceptedFormats: ['.doc', '.docx'],
      },
      {
        id: 'from-excel',
        label: 'Excel → PDF',
        description: 'Turn XLSX and XLS spreadsheets and workbooks into neat printable PDFs.',
        capabilitySlug: 'excel-to-pdf',
        aliases: ['xlsx to pdf', 'sheets to pdf'],
        acceptedFormats: ['.xls', '.xlsx'],
      },
      {
        id: 'from-powerpoint',
        label: 'PowerPoint → PDF',
        description: 'Export PPTX presentation slide decks directly into PDF handouts.',
        capabilitySlug: 'powerpoint-to-pdf',
        aliases: ['pptx to pdf', 'slides to pdf'],
        acceptedFormats: ['.ppt', '.pptx'],
      },
      {
        id: 'from-jpg',
        label: 'JPG → PDF',
        description: 'Convert JPEG photos into a clean, compact PDF document.',
        capabilitySlug: 'jpg-to-pdf',
        aliases: ['jpeg to pdf', 'photo to pdf'],
        acceptedFormats: ['.jpg', '.jpeg'],
      },
      {
        id: 'from-png',
        label: 'PNG → PDF',
        description: 'Pack high-resolution PNG images into standard PDF pages.',
        capabilitySlug: 'png-to-pdf',
        aliases: ['pngs to pdf'],
        acceptedFormats: ['.png'],
      },
      {
        id: 'from-images',
        label: 'Images → PDF',
        description: 'Combine multiple mixed images (JPG, PNG, WebP) into a single PDF album.',
        capabilitySlug: 'images-to-pdf',
        aliases: ['photos to pdf', 'batch images to pdf'],
        acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp'],
      },
      {
        id: 'from-html',
        label: 'HTML → PDF',
        description: 'Render web pages or raw HTML files into vector-perfect PDFs.',
        capabilitySlug: 'html-to-pdf',
        aliases: ['webpage to pdf', 'url to pdf'],
        acceptedFormats: ['.html', '.htm'],
      },
      {
        id: 'from-document',
        label: 'Document → PDF',
        description: 'Universal document converter supporting ODT, RTF, and text files.',
        capabilitySlug: 'document-to-pdf',
        aliases: ['doc converter', 'office to pdf'],
        acceptedFormats: ['.odt', '.rtf', '.txt'],
      },
      {
        id: 'from-rtf',
        label: 'RTF → PDF',
        description: 'Convert Rich Text Format manuscripts into standardized PDF documents.',
        capabilitySlug: 'rtf-to-pdf',
        aliases: ['rich text to pdf'],
        acceptedFormats: ['.rtf'],
      },
      {
        id: 'from-text',
        label: 'Text → PDF',
        description: 'Wrap raw plaintext files (.txt) into clean formatted PDF sheets.',
        capabilitySlug: 'text-to-pdf',
        aliases: ['txt to pdf'],
        acceptedFormats: ['.txt'],
      },
      {
        id: 'from-xml',
        label: 'XML → PDF',
        description: 'Format raw XML data trees into readable, styled PDF tables.',
        capabilitySlug: 'xml-to-pdf',
        aliases: ['xml document to pdf'],
        acceptedFormats: ['.xml'],
      },
      {
        id: 'from-json',
        label: 'JSON → PDF',
        description: 'Render structured JSON records into attractive printable reports.',
        capabilitySlug: 'json-to-pdf',
        aliases: ['json to pdf report'],
        acceptedFormats: ['.json'],
      },
    ],
  },
  {
    id: 'ws-pdf-advanced',
    slug: 'pdf-advanced',
    name: 'Advanced PDF',
    category: 'pdf',
    description: 'Optical Character Recognition (OCR), document side-by-side comparison, and language translation.',
    icon: 'Sparkles',
    defaultModeId: 'ocr',
    searchableAliases: ['ocr pdf', 'compare pdf', 'translate pdf', 'searchable pdf'],
    capabilitySlugs: ['ocr-pdf', 'compare-pdf', 'translate-pdf'],
    modes: [
      {
        id: 'ocr',
        label: 'OCR PDF',
        description: 'Transform scanned image documents into selectable, searchable text.',
        capabilitySlug: 'ocr-pdf',
        aliases: ['optical character recognition', 'make pdf searchable'],
      },
      {
        id: 'compare',
        label: 'Compare PDF',
        description: 'Visual side-by-side diff highlighting text and graphic alterations.',
        capabilitySlug: 'compare-pdf',
        aliases: ['diff pdf', 'compare versions'],
      },
      {
        id: 'translate',
        label: 'Translate PDF',
        description: 'Translate document paragraphs into different languages with layout preservation.',
        capabilitySlug: 'translate-pdf',
        aliases: ['translate document', 'language converter'],
      },
    ],
  },
  {
    id: 'ws-pdf-a',
    slug: 'pdf-a',
    name: 'PDF/A',
    category: 'pdf',
    description: 'ISO 19005 compliant long-term electronic archiving validation and conversion.',
    icon: 'ShieldCheck',
    defaultModeId: 'convert',
    searchableAliases: ['validate pdf/a', 'convert to pdf/a', 'iso 19005', 'archival pdf'],
    capabilitySlugs: ['validate-pdf-a', 'convert-to-pdf-a'],
    modes: [
      {
        id: 'validate',
        label: 'Validate PDF/A',
        description: 'Audit document compliance against veraPDF ISO 19005 archival standards.',
        capabilitySlug: 'validate-pdf-a',
        aliases: ['verapdf test', 'check pdf/a'],
      },
      {
        id: 'convert',
        label: 'Convert to PDF/A',
        description: 'Embed color intents, metadata schemas, and fonts for compliant long-term storage.',
        capabilitySlug: 'convert-to-pdf-a',
        aliases: ['pdf/a-1b converter', 'archive format'],
      },
    ],
  },
  {
    id: 'ws-batch-pdf',
    slug: 'batch-pdf',
    name: 'Batch PDF',
    category: 'pdf',
    description: 'Perform bulk transformations, multi-file rotations, and automated queue jobs.',
    icon: 'Cpu',
    defaultModeId: 'batch-operations',
    searchableAliases: ['batch pdf', 'bulk pdf processing', 'multi-file queue'],
    capabilitySlugs: ['batch-pdf-operations'],
    modes: [
      {
        id: 'batch-operations',
        label: 'Batch PDF Operations',
        description: 'Execute conversions, watermarking, and compression over dozens of files simultaneously.',
        capabilitySlug: 'batch-pdf-operations',
        aliases: ['bulk process', 'queue operations'],
      },
    ],
  },
];
