import { PublicWorkspace } from './workspace-types';

export const textWorkspaces: PublicWorkspace[] = [
  {
    id: 'ws-text-analyzer',
    slug: 'text-analyzer',
    name: 'Text Analyzer',
    category: 'text',
    description: 'Detailed real-time text analysis: count words, characters, sentences, reading time, and extract emails and URLs.',
    icon: 'FileSearch',
    defaultModeId: 'word-counter',
    badge: 'Popular',
    searchableAliases: ['word counter', 'character counter', 'text statistics', 'extract emails', 'extract urls'],
    capabilitySlugs: ['word-counter', 'text-extractor'],
    modes: [
      {
        id: 'word-counter',
        label: 'Word & Text Counter',
        description: 'Detailed real-time text analysis. Count words, characters, sentences, paragraphs, and estimate reading time.',
        capabilitySlug: 'word-counter',
        aliases: ['word count', 'character count', 'reading time calculator'],
      },
      {
        id: 'text-extractor',
        label: 'Extract Emails, URLs & Numbers',
        description: 'Extract email addresses, web links, numbers, hashtags, and @mentions from unformatted text documents.',
        capabilitySlug: 'text-extractor',
        aliases: ['email scraper', 'url extractor', 'find numbers in text'],
      },
    ],
  },
  {
    id: 'ws-text-formatter',
    slug: 'text-formatter',
    name: 'Text Formatter',
    category: 'text',
    description: 'Transform casing (UPPERCASE, lowercase, Title Case, camelCase), sort lines, reverse text, and manage line numbers.',
    icon: 'Type',
    defaultModeId: 'case-converter',
    searchableAliases: ['case converter', 'uppercase', 'lowercase', 'title case', 'sort lines', 'line numbers'],
    capabilitySlugs: ['case-converter', 'sort-lines', 'reverse-text', 'line-numbers'],
    modes: [
      {
        id: 'case-converter',
        label: 'Text Case Converter',
        description: 'Transform text into 9 capitalization formats: UPPERCASE, lowercase, Title Case, camelCase, snake_case, etc.',
        capabilitySlug: 'case-converter',
        aliases: ['change case', 'capitalize text', 'camelcase converter'],
      },
      {
        id: 'sort-lines',
        label: 'Sort Lines',
        description: 'Sort lines alphabetically (A-Z, Z-A), numerically, or by line length with case-sensitivity options.',
        capabilitySlug: 'sort-lines',
        aliases: ['alphabetize list', 'order lines', 'sort text'],
      },
      {
        id: 'reverse-text',
        label: 'Reverse Text & Lines',
        description: 'Reverse text characters or flip line ordering from bottom to top with one click.',
        capabilitySlug: 'reverse-text',
        aliases: ['backwards text', 'flip lines upside down'],
      },
      {
        id: 'line-numbers',
        label: 'Add / Remove Line Numbers',
        description: 'Add sequential line numbering with custom separators or strip existing line numbers from text snippets.',
        capabilitySlug: 'line-numbers',
        aliases: ['number lines', 'strip line numbers'],
      },
    ],
  },
  {
    id: 'ws-text-cleaner',
    slug: 'text-cleaner',
    name: 'Text Cleaner',
    category: 'text',
    description: 'Clean up dirty lists and documents by removing duplicate rows, trimming redundant whitespace, and collapsing spaces.',
    icon: 'Sparkles',
    defaultModeId: 'duplicate-line-remover',
    searchableAliases: ['remove duplicate lines', 'clean whitespace', 'trim text', 'remove blank lines'],
    capabilitySlugs: ['duplicate-line-remover', 'whitespace-cleaner'],
    modes: [
      {
        id: 'duplicate-line-remover',
        label: 'Duplicate Line Remover',
        description: 'Clean text lists and data files by eliminating duplicate lines with case-sensitivity and whitespace options.',
        capabilitySlug: 'duplicate-line-remover',
        aliases: ['dedupe lines', 'unique lines filter'],
      },
      {
        id: 'whitespace-cleaner',
        label: 'Whitespace Cleaner & Trimmer',
        description: 'Clean up formatted text by stripping redundant whitespace, collapsing multiple spaces, and removing empty lines.',
        capabilitySlug: 'whitespace-cleaner',
        aliases: ['strip spaces', 'remove empty lines', 'trim spaces'],
      },
    ],
  },
  {
    id: 'ws-text-compare',
    slug: 'text-compare',
    name: 'Text Compare',
    category: 'text',
    description: 'Visual side-by-side text and code diff comparison tool with color-coded additions, deletions, and line numbers.',
    icon: 'GitCompare',
    defaultModeId: 'text-diff',
    searchableAliases: ['text diff', 'compare text', 'diff checker', 'code diff', 'side by side compare'],
    capabilitySlugs: ['text-diff'],
    modes: [
      {
        id: 'text-diff',
        label: 'Text Diff & Comparison Tool',
        description: 'Compare two text documents or code snippets side-by-side with color-coded additions, deletions, and line numbers.',
        capabilitySlug: 'text-diff',
        aliases: ['diff checker', 'compare text files', 'string comparison'],
      },
    ],
  },
  {
    id: 'ws-text-generator',
    slug: 'text-generator',
    name: 'Text Converter & Generator',
    category: 'text',
    description: 'Generate customizable Lorem Ipsum placeholder dummy copy and convert titles into web-safe, SEO-friendly URL slugs.',
    icon: 'Wand2',
    defaultModeId: 'slug-generator',
    searchableAliases: ['slug generator', 'lorem ipsum generator', 'placeholder text', 'url slug maker'],
    capabilitySlugs: ['slug-generator', 'lorem-ipsum-generator'],
    modes: [
      {
        id: 'slug-generator',
        label: 'URL Slug Generator',
        description: 'Convert headlines and titles into clean, web-safe, SEO-friendly URL slugs with custom separators.',
        capabilitySlug: 'slug-generator',
        aliases: ['slugify', 'url title maker', 'permalink generator'],
      },
      {
        id: 'lorem-ipsum-generator',
        label: 'Lorem Ipsum Generator',
        description: 'Generate customizable placeholder dummy text in paragraphs, sentences, words, or HTML lists.',
        capabilitySlug: 'lorem-ipsum-generator',
        aliases: ['dummy text', 'placeholder copy', 'lipsum generator'],
      },
    ],
  },
];
